import { VideoInputForm } from "@/components/app/video-input-form";
import { Header } from "@/components/base/header";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { Textarea } from "@/components/ui/textarea";
import { Wand2 } from "lucide-react";

export function App() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 p-6 flex gap-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="grid grid-rows-2 gap-4 flex-1">
            <Textarea className="resize-none p-4 leading-relaxed" placeholder="Include the prompt for the AI..." />
            <Textarea className="resize-none p-4 leading-relaxed" placeholder="Output generated by AI..." readOnly />
          </div>
          <p className="text-sm text-muted-foreground">Remember: you could use the variable <code className="text-green400">{ 'transcription' }</code> in you r prompt to add the selected video transcription content.</p>
        </div>

        <aside className="w-80 space-y-6">
          <VideoInputForm />

          <Separator />

          <form className="space-y-4">
            <div className="space-y-2">
              <Label>Prompt</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select a prompt" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="title">YouTube title</SelectItem>
                  <SelectItem value="description">YouTube description</SelectItem>
                </SelectContent>
              </Select>
              <span className="block text-xs text-muted-foreground italic">You will could customise this option soon.</span>
            </div>

            <div className="space-y-2">
              <Label>Model</Label>
              <Select disabled defaultValue="gpt3.5">
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="gpt3.5">GPT 3.5</SelectItem>
                </SelectContent>
              </Select>
              <span className="block text-xs text-muted-foreground italic">You will could customise this option soon.</span>
            </div>
          </form>

          <Separator />

          <form className="space-y-4">
            <div className="space-y-4">
              <Label>Temperature</Label>
              <Slider min={0} max={1} step={0.1} />
              <span className="block text-xs text-muted-foreground italic leading-relaxed">High values tend to leave the content more creative and mor e prone to errors.</span>
            </div>
          </form>

          <Separator />

          <Button type="submit" className="w-full">
            Submit
            <Wand2 className="w-4 h-4 ml-2" />
          </Button>
        </aside>
      </main>
    </div>
  )
}
